### PR TITLE
testdata dir added

### PR DESCRIPTION
**Pull request by saptarsi96**

### CODE REVIEW

**Comment by thiagonache** [comment]
Hi @saptarsi96,

Thank you very much for the contribution. Can you update the test code too, please?

**Comment by thiagonache** [comment]
@saptarsi96 We have two entries in the file https://github.com/thiagonache/terraformtest/blob/master/terraformtest_test.go that uses terraform.tfplan, we need to update them to the new path also.

Let me know if I can help with anything. 

Thank you!

**Review by thiagonache — CHANGES_REQUESTED** [review]
Thank you for the contribution.
Please, update the two references of `terraform.tfplan` in `terraformtest_test.go` to the new path `testdata/terraform.tfplan`

**Comment by saptarsi96** [comment]
@thiagonache Please check the **linting** errors as I think you have some unused variables for which these red flags have been raised.

**Comment by thiagonache** [comment]
the error is being handled in another PR

**Pull request merged**
